export const SRI_LANKA_MAIN_CITIES = [
  'Colombo 01 - Fort',
  'Colombo 02 - Slave Island',
  'Colombo 03 - Kollupitiya',
  'Colombo 04 - Bambalapitiya',
  'Colombo 05 - Havelock Town',
  'Colombo 06 - Wellawatte',
  'Colombo 07 - Cinnamon Gardens',
  'Colombo 08 - Borella',
  'Colombo 09 - Dematagoda',
  'Colombo 10 - Maradana',
  'Colombo 11 - Pettah',
  'Colombo 12 - Hulftsdorp',
  'Colombo 13 - Kotahena',
  'Colombo 14 - Grandpass',
  'Colombo 15 - Mutwal',
  'Dehiwala',
  'Mount Lavinia',
  'Nugegoda',
  'Maharagama',
  'Kottawa',
  'Malabe',
  'Battaramulla',
  'Homagama',
  'Moratuwa',
  'Piliyandala',
  'Gampaha',
  'Negombo',
  'Ja-Ela',
  'Wattala',
  'Kelaniya',
  'Kiribathgoda',
  'Kadawatha',
  'Minuwangoda',
  'Nittambuwa',
  'Kandana',
  'Kalutara',
  'Panadura',
  'Beruwala',
  'Avissawella',
  'Kandy',
  'Peradeniya',
  'Gampola',
  'Matale',
  'Nuwara Eliya',
  'Galle',
  'Hikkaduwa',
  'Matara',
  'Tangalle',
  'Hambantota',
  'Jaffna',
  'Kilinochchi',
  'Mannar',
  'Vavuniya',
  'Trincomalee',
  'Batticaloa',
  'Ampara',
  'Kurunegala',
  'Chilaw',
  'Puttalam',
  'Anuradhapura',
  'Polonnaruwa',
  'Badulla',
  'Bandarawela',
  'Monaragala',
  'Ratnapura',
  'Kegalle',
];
